kind: Cluster
metadata:
  name: infra-test-utkarsh
  project: defaultproject
spec:
  blueprint: default
  cloudprovider: Utkarsh-AWS
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: infra-test-utkarsh
  region: us-west-2
  version: "1.19"
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
      efs: true
      externalDNS: true
      imageBuilder: true
  instanceType: t3.xlarge
  maxSize: 2
  minSize: 2
  name: ng-50ee924d
  volumeSize: 80
  volumeType: gp3
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
