kind: Cluster
metadata:
  name: madhutesteks2
  project: dev1
spec:
  blueprint: default
  cloudprovider: stscluster
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: madhutesteks2
  region: us-west-1
  tags:
    madhu: tag123
  version: "1.18"
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      autoScaler: true
      imageBuilder: true
  instanceType: t3.xlarge
  labels:
    madhul: l1
  maxSize: 2
  minSize: 1
  name: ng1
  volumeSize: 80
  volumeType: gp3
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
