kind: Cluster
metadata:
  name: madhutesteks2
  project: dev1
spec:
  blueprint: eks-bp
  blueprintversion: v0
  cloudprovider: aws
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: madhutesteks2
  region: us-west-1
  version: "1.18"
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      autoScaler: true
      imageBuilder: true
  instanceType: t3.xlarge
  maxSize: 2
  minSize: 1
  name: ng-449cae37
  ssh:
    allow: true
    publicKeyName: madhu
  volumeSize: 80
  volumeType: gp3
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  nat:
    gateway: Single
